export const FETCHING_DATA = "FETCHING_DATA"
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE"
export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";
export const FETCHING_DATA_PEOPLE_SUCCESS = "FETCHING_DATA_PEOPLE_SUCCESS";

/* PROMOTIONS */

export const FETCHING_PROMOTIONS = "FETCHING_PROMOTIONS"


/* UI */ 
export const SHOW_TOAST = "SHOW_TOAST"
export const HIDDE_TOAST = "HIDDE_TOAST"
